# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addNewMember.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(827, 567)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 789, 818))
        self.scrollAreaWidgetContents.setStyleSheet("margin: 5px;\n"
"margin-right: 30px;\n"
"margin-left: 0px;\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameLineEdit.setPlaceholderText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fatherLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fatherLineEdit.setObjectName("fatherLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fatherLineEdit)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dobDateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dobDateEdit.setCalendarPopup(True)
        self.dobDateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.dobDateEdit.setObjectName("dobDateEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dobDateEdit)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.genderComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.genderComboBox)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.villageLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.villageLineEdit.setObjectName("villageLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.villageLineEdit)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.blockLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.blockLineEdit.setObjectName("blockLineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.blockLineEdit)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.districtLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.districtLineEdit.setObjectName("districtLineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.districtLineEdit)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.stateLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.stateLineEdit)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.pinCodeLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.pinCodeLineEdit.setObjectName("pinCodeLineEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pinCodeLineEdit)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.mobileLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.mobileLineEdit.setObjectName("mobileLineEdit")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.mobileLineEdit)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.emailLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.professionLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.professionLineEdit.setObjectName("professionLineEdit")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.professionLineEdit)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.officeLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.officeLineEdit.setObjectName("officeLineEdit")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.officeLineEdit)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.membershipTypeComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.membershipTypeComboBox.setObjectName("membershipTypeComboBox")
        self.membershipTypeComboBox.addItem("")
        self.membershipTypeComboBox.addItem("")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.membershipTypeComboBox)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.membershipFeeLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.membershipFeeLineEdit.setObjectName("membershipFeeLineEdit")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.membershipFeeLineEdit)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.numberOfShareLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.numberOfShareLineEdit.setObjectName("numberOfShareLineEdit")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.numberOfShareLineEdit)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.currentRateLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.currentRateLineEdit.setObjectName("currentRateLineEdit")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.currentRateLineEdit)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.paybleAmountLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.paybleAmountLineEdit.setObjectName("paybleAmountLineEdit")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.FieldRole, self.paybleAmountLineEdit)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(32, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.openingDateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.openingDateEdit.setCalendarPopup(True)
        self.openingDateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.openingDateEdit.setObjectName("openingDateEdit")
        self.formLayout_2.setWidget(32, QtWidgets.QFormLayout.FieldRole, self.openingDateEdit)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.photoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.photoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.photoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.photoLabel.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.photoLabel.setScaledContents(True)
        self.photoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.photoLabel.setObjectName("photoLabel")
        self.verticalLayout_2.addWidget(self.photoLabel)
        self.uploadPhotoPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.uploadPhotoPushButton.setObjectName("uploadPhotoPushButton")
        self.verticalLayout_2.addWidget(self.uploadPhotoPushButton)
        self.signatureLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.signatureLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.signatureLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.signatureLabel.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.signatureLabel.setScaledContents(True)
        self.signatureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.signatureLabel.setObjectName("signatureLabel")
        self.verticalLayout_2.addWidget(self.signatureLabel)
        self.uploadSignPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.uploadSignPushButton.setObjectName("uploadSignPushButton")
        self.verticalLayout_2.addWidget(self.uploadSignPushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.addNewPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.addNewPushButton.setObjectName("addNewPushButton")
        self.verticalLayout_2.addWidget(self.addNewPushButton)
        self.updatePushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.updatePushButton.setObjectName("updatePushButton")
        self.verticalLayout_2.addWidget(self.updatePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.verticalLayout_2.addWidget(self.cancelPushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New Member"))
        self.label.setText(_translate("Form", "NAME:"))
        self.label_2.setText(_translate("Form", "FATHER/HUSBAND"))
        self.label_3.setText(_translate("Form", "DOB:"))
        self.label_4.setText(_translate("Form", "GENDER:"))
        self.genderComboBox.setItemText(0, _translate("Form", "MALE"))
        self.genderComboBox.setItemText(1, _translate("Form", "FEMALE"))
        self.label_5.setText(_translate("Form", "VILLAGE:"))
        self.label_6.setText(_translate("Form", "BLOCK:"))
        self.label_7.setText(_translate("Form", "DISTRICT:"))
        self.label_8.setText(_translate("Form", "STATE:"))
        self.label_9.setText(_translate("Form", "PIN CODE"))
        self.label_10.setText(_translate("Form", "MOBILE:"))
        self.label_11.setText(_translate("Form", "EMAIL"))
        self.label_12.setText(_translate("Form", "PROFESSION"))
        self.label_13.setText(_translate("Form", "OFFICE:"))
        self.label_16.setText(_translate("Form", "MEMBERSHIP TYPE:"))
        self.membershipTypeComboBox.setItemText(0, _translate("Form", "SHAREHOLDER"))
        self.membershipTypeComboBox.setItemText(1, _translate("Form", "NOMINAL MEMBER"))
        self.label_20.setText(_translate("Form", "MEMBERSHIP FEE:"))
        self.label_17.setText(_translate("Form", "NUMBER OF SHARE"))
        self.label_18.setText(_translate("Form", "CURRENT RATE OF SHARE"))
        self.label_19.setText(_translate("Form", "PAYBLE AMOUNT:"))
        self.label_21.setText(_translate("Form", "OPENING DATE:"))
        self.photoLabel.setText(_translate("Form", "Photo"))
        self.uploadPhotoPushButton.setText(_translate("Form", "Upload Photo"))
        self.signatureLabel.setText(_translate("Form", "Signature"))
        self.uploadSignPushButton.setText(_translate("Form", "Upload Signature"))
        self.addNewPushButton.setText(_translate("Form", "ADD NEW"))
        self.updatePushButton.setText(_translate("Form", "UPDATE"))
        self.cancelPushButton.setText(_translate("Form", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

