# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addNewMember.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(771, 766)
        self.formLayout_2 = QtWidgets.QFormLayout(Form)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameLineEdit = QtWidgets.QLineEdit(Form)
        self.nameLineEdit.setPlaceholderText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fatherLineEdit = QtWidgets.QLineEdit(Form)
        self.fatherLineEdit.setObjectName("fatherLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fatherLineEdit)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dobDateEdit = QtWidgets.QDateEdit(Form)
        self.dobDateEdit.setCalendarPopup(True)
        self.dobDateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.dobDateEdit.setObjectName("dobDateEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dobDateEdit)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.genderComboBox = QtWidgets.QComboBox(Form)
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.genderComboBox)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.villageLineEdit = QtWidgets.QLineEdit(Form)
        self.villageLineEdit.setObjectName("villageLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.villageLineEdit)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.blockLineEdit = QtWidgets.QLineEdit(Form)
        self.blockLineEdit.setObjectName("blockLineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.blockLineEdit)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.districtLineEdit = QtWidgets.QLineEdit(Form)
        self.districtLineEdit.setObjectName("districtLineEdit")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.districtLineEdit)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.stateLineEdit = QtWidgets.QLineEdit(Form)
        self.stateLineEdit.setObjectName("stateLineEdit")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.stateLineEdit)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.pinCodeLineEdit = QtWidgets.QLineEdit(Form)
        self.pinCodeLineEdit.setObjectName("pinCodeLineEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pinCodeLineEdit)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.mobileLineEdit = QtWidgets.QLineEdit(Form)
        self.mobileLineEdit.setObjectName("mobileLineEdit")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.mobileLineEdit)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.emailLineEdit = QtWidgets.QLineEdit(Form)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.professionLineEdit = QtWidgets.QLineEdit(Form)
        self.professionLineEdit.setObjectName("professionLineEdit")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.professionLineEdit)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.officeLineEdit = QtWidgets.QLineEdit(Form)
        self.officeLineEdit.setObjectName("officeLineEdit")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.officeLineEdit)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.membershipTypeComboBox = QtWidgets.QComboBox(Form)
        self.membershipTypeComboBox.setObjectName("membershipTypeComboBox")
        self.membershipTypeComboBox.addItem("")
        self.membershipTypeComboBox.addItem("")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.membershipTypeComboBox)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.membershipFeeLineEdit = QtWidgets.QLineEdit(Form)
        self.membershipFeeLineEdit.setObjectName("membershipFeeLineEdit")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.membershipFeeLineEdit)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.numberOfShareLineEdit = QtWidgets.QLineEdit(Form)
        self.numberOfShareLineEdit.setObjectName("numberOfShareLineEdit")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.numberOfShareLineEdit)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.currentRateLineEdit = QtWidgets.QLineEdit(Form)
        self.currentRateLineEdit.setObjectName("currentRateLineEdit")
        self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.currentRateLineEdit)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(29, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.paybleAmountLineEdit = QtWidgets.QLineEdit(Form)
        self.paybleAmountLineEdit.setObjectName("paybleAmountLineEdit")
        self.formLayout_2.setWidget(29, QtWidgets.QFormLayout.FieldRole, self.paybleAmountLineEdit)
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(33, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.openingDateEdit = QtWidgets.QDateEdit(Form)
        self.openingDateEdit.setCalendarPopup(True)
        self.openingDateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.openingDateEdit.setObjectName("openingDateEdit")
        self.formLayout_2.setWidget(33, QtWidgets.QFormLayout.FieldRole, self.openingDateEdit)
        self.addNewPushButton = QtWidgets.QPushButton(Form)
        self.addNewPushButton.setObjectName("addNewPushButton")
        self.formLayout_2.setWidget(40, QtWidgets.QFormLayout.FieldRole, self.addNewPushButton)
        self.updatePushButton = QtWidgets.QPushButton(Form)
        self.updatePushButton.setObjectName("updatePushButton")
        self.formLayout_2.setWidget(41, QtWidgets.QFormLayout.FieldRole, self.updatePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(Form)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.formLayout_2.setWidget(42, QtWidgets.QFormLayout.FieldRole, self.cancelPushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New Member"))
        self.label.setText(_translate("Form", "NAME:"))
        self.label_2.setText(_translate("Form", "FATHER/HUSBAND"))
        self.label_3.setText(_translate("Form", "DOB:"))
        self.label_4.setText(_translate("Form", "GENDER:"))
        self.genderComboBox.setItemText(0, _translate("Form", "MALE"))
        self.genderComboBox.setItemText(1, _translate("Form", "FEMALE"))
        self.label_5.setText(_translate("Form", "VILLAGE:"))
        self.label_6.setText(_translate("Form", "BLOCK:"))
        self.label_7.setText(_translate("Form", "DISTRICT:"))
        self.label_8.setText(_translate("Form", "STATE:"))
        self.label_9.setText(_translate("Form", "PIN CODE"))
        self.label_10.setText(_translate("Form", "MOBILE:"))
        self.label_11.setText(_translate("Form", "EMAIL"))
        self.label_12.setText(_translate("Form", "PROFESSION"))
        self.label_13.setText(_translate("Form", "OFFICE:"))
        self.label_14.setText(_translate("Form", "PHOTO"))
        self.label_15.setText(_translate("Form", "SIGNATURE"))
        self.label_16.setText(_translate("Form", "MEMBERSHIP TYPE:"))
        self.membershipTypeComboBox.setItemText(0, _translate("Form", "SHAREHOLDER"))
        self.membershipTypeComboBox.setItemText(1, _translate("Form", "NOMINAL MEMBER"))
        self.label_20.setText(_translate("Form", "MEMBERSHIP FEE:"))
        self.label_17.setText(_translate("Form", "NUMBER OF SHARE"))
        self.label_18.setText(_translate("Form", "CURRENT RATE OF SHARE"))
        self.label_19.setText(_translate("Form", "PAYBLE AMOUNT:"))
        self.label_21.setText(_translate("Form", "OPENING DATE:"))
        self.addNewPushButton.setText(_translate("Form", "ADD NEW"))
        self.updatePushButton.setText(_translate("Form", "UPDATE"))
        self.cancelPushButton.setText(_translate("Form", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

