# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memberPage.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_memberPage(object):
    def setupUi(self, memberPage):
        memberPage.setObjectName("memberPage")
        memberPage.resize(512, 719)
        self.gridLayout = QtWidgets.QGridLayout(memberPage)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(memberPage)
        font = QtGui.QFont()
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.infoTab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_photo = QtWidgets.QLabel(self.infoTab)
        self.label_photo.setMinimumSize(QtCore.QSize(100, 100))
        self.label_photo.setMaximumSize(QtCore.QSize(100, 100))
        self.label_photo.setStyleSheet("background-color: white;")
        self.label_photo.setText("")
        self.label_photo.setScaledContents(True)
        self.label_photo.setObjectName("label_photo")
        self.verticalLayout.addWidget(self.label_photo)
        self.label_photoField = QtWidgets.QLabel(self.infoTab)
        self.label_photoField.setMaximumSize(QtCore.QSize(200, 200))
        self.label_photoField.setText("")
        self.label_photoField.setObjectName("label_photoField")
        self.verticalLayout.addWidget(self.label_photoField)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_signature = QtWidgets.QLabel(self.infoTab)
        self.label_signature.setMinimumSize(QtCore.QSize(100, 100))
        self.label_signature.setMaximumSize(QtCore.QSize(100, 100))
        self.label_signature.setStyleSheet("background-color: white;\n"
"")
        self.label_signature.setText("")
        self.label_signature.setScaledContents(True)
        self.label_signature.setObjectName("label_signature")
        self.verticalLayout.addWidget(self.label_signature)
        self.label_signatureField = QtWidgets.QLabel(self.infoTab)
        self.label_signatureField.setMaximumSize(QtCore.QSize(200, 200))
        self.label_signatureField.setText("")
        self.label_signatureField.setObjectName("label_signatureField")
        self.verticalLayout.addWidget(self.label_signatureField)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(-1, 20, -1, -1)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(self.infoTab)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.label_nameField = QtWidgets.QLabel(self.infoTab)
        self.label_nameField.setObjectName("label_nameField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_nameField)
        self.label_fatherHusband = QtWidgets.QLabel(self.infoTab)
        self.label_fatherHusband.setObjectName("label_fatherHusband")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_fatherHusband)
        self.label_fatherHusbandField = QtWidgets.QLabel(self.infoTab)
        self.label_fatherHusbandField.setObjectName("label_fatherHusbandField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_fatherHusbandField)
        self.label_dob = QtWidgets.QLabel(self.infoTab)
        self.label_dob.setObjectName("label_dob")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_dob)
        self.label_dobField = QtWidgets.QLabel(self.infoTab)
        self.label_dobField.setObjectName("label_dobField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_dobField)
        self.label_gender = QtWidgets.QLabel(self.infoTab)
        self.label_gender.setObjectName("label_gender")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_gender)
        self.label_genderField = QtWidgets.QLabel(self.infoTab)
        self.label_genderField.setObjectName("label_genderField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_genderField)
        self.label_village = QtWidgets.QLabel(self.infoTab)
        self.label_village.setObjectName("label_village")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_village)
        self.label_villageField = QtWidgets.QLabel(self.infoTab)
        self.label_villageField.setObjectName("label_villageField")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_villageField)
        self.label_block = QtWidgets.QLabel(self.infoTab)
        self.label_block.setObjectName("label_block")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_block)
        self.label_blockField = QtWidgets.QLabel(self.infoTab)
        self.label_blockField.setObjectName("label_blockField")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_blockField)
        self.label_district = QtWidgets.QLabel(self.infoTab)
        self.label_district.setObjectName("label_district")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_district)
        self.label_districtField = QtWidgets.QLabel(self.infoTab)
        self.label_districtField.setObjectName("label_districtField")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_districtField)
        self.label_state = QtWidgets.QLabel(self.infoTab)
        self.label_state.setObjectName("label_state")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_state)
        self.label_stateField = QtWidgets.QLabel(self.infoTab)
        self.label_stateField.setObjectName("label_stateField")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_stateField)
        self.label_pincode = QtWidgets.QLabel(self.infoTab)
        self.label_pincode.setObjectName("label_pincode")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_pincode)
        self.label_pincodeField = QtWidgets.QLabel(self.infoTab)
        self.label_pincodeField.setObjectName("label_pincodeField")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_pincodeField)
        self.label_mobile = QtWidgets.QLabel(self.infoTab)
        self.label_mobile.setObjectName("label_mobile")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_mobile)
        self.label_mobileField = QtWidgets.QLabel(self.infoTab)
        self.label_mobileField.setObjectName("label_mobileField")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_mobileField)
        self.label_email = QtWidgets.QLabel(self.infoTab)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.label_emailField = QtWidgets.QLabel(self.infoTab)
        self.label_emailField.setObjectName("label_emailField")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_emailField)
        self.label_profession = QtWidgets.QLabel(self.infoTab)
        self.label_profession.setObjectName("label_profession")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_profession)
        self.label_professionField = QtWidgets.QLabel(self.infoTab)
        self.label_professionField.setObjectName("label_professionField")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.label_professionField)
        self.label_office = QtWidgets.QLabel(self.infoTab)
        self.label_office.setObjectName("label_office")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_office)
        self.label_officeField = QtWidgets.QLabel(self.infoTab)
        self.label_officeField.setObjectName("label_officeField")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.label_officeField)
        self.label_membershipType = QtWidgets.QLabel(self.infoTab)
        self.label_membershipType.setObjectName("label_membershipType")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_membershipType)
        self.label_membershipTypeField = QtWidgets.QLabel(self.infoTab)
        self.label_membershipTypeField.setObjectName("label_membershipTypeField")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.label_membershipTypeField)
        self.label_shares = QtWidgets.QLabel(self.infoTab)
        self.label_shares.setObjectName("label_shares")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_shares)
        self.label_sharesField = QtWidgets.QLabel(self.infoTab)
        self.label_sharesField.setObjectName("label_sharesField")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.label_sharesField)
        self.label_openingDate = QtWidgets.QLabel(self.infoTab)
        self.label_openingDate.setObjectName("label_openingDate")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_openingDate)
        self.label_openingDateField = QtWidgets.QLabel(self.infoTab)
        self.label_openingDateField.setObjectName("label_openingDateField")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.label_openingDateField)
        self.editButton = QtWidgets.QPushButton(self.infoTab)
        self.editButton.setObjectName("editButton")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.editButton)
        self.label = QtWidgets.QLabel(self.infoTab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_idProof = QtWidgets.QLabel(self.infoTab)
        self.label_idProof.setObjectName("label_idProof")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.label_idProof)
        self.label_2 = QtWidgets.QLabel(self.infoTab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_idNumber = QtWidgets.QLabel(self.infoTab)
        self.label_idNumber.setObjectName("label_idNumber")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label_idNumber)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.infoTab, "")
        self.loanTab = QtWidgets.QWidget()
        self.loanTab.setObjectName("loanTab")
        self.tabWidget.addTab(self.loanTab, "")
        self.accountsTab = QtWidgets.QWidget()
        self.accountsTab.setObjectName("accountsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.accountsTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fixedDepositWidget = QtWidgets.QWidget(self.accountsTab)
        self.fixedDepositWidget.setObjectName("fixedDepositWidget")
        self.fixedDepositVerticalLayout = QtWidgets.QVBoxLayout(self.fixedDepositWidget)
        self.fixedDepositVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.fixedDepositVerticalLayout.setObjectName("fixedDepositVerticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.fixedDepositWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.fDeletePushButton = QtWidgets.QPushButton(self.fixedDepositWidget)
        self.fDeletePushButton.setObjectName("fDeletePushButton")
        self.horizontalLayout_9.addWidget(self.fDeletePushButton)
        self.fixedDepositVerticalLayout.addLayout(self.horizontalLayout_9)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.fixedDepositWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fAccountNoLineEdit = QtWidgets.QLineEdit(self.fixedDepositWidget)
        self.fAccountNoLineEdit.setReadOnly(True)
        self.fAccountNoLineEdit.setObjectName("fAccountNoLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fAccountNoLineEdit)
        self.label_5 = QtWidgets.QLabel(self.fixedDepositWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fPrincipalAmountLineEdit = QtWidgets.QLineEdit(self.fixedDepositWidget)
        self.fPrincipalAmountLineEdit.setReadOnly(True)
        self.fPrincipalAmountLineEdit.setObjectName("fPrincipalAmountLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fPrincipalAmountLineEdit)
        self.label_7 = QtWidgets.QLabel(self.fixedDepositWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.fOpeningDateEdit = QtWidgets.QDateEdit(self.fixedDepositWidget)
        self.fOpeningDateEdit.setReadOnly(True)
        self.fOpeningDateEdit.setObjectName("fOpeningDateEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fOpeningDateEdit)
        self.label_6 = QtWidgets.QLabel(self.fixedDepositWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.fMaturityDateEdit = QtWidgets.QDateEdit(self.fixedDepositWidget)
        self.fMaturityDateEdit.setReadOnly(True)
        self.fMaturityDateEdit.setObjectName("fMaturityDateEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fMaturityDateEdit)
        self.label_8 = QtWidgets.QLabel(self.fixedDepositWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.fMaturityAmountLineEdit = QtWidgets.QLineEdit(self.fixedDepositWidget)
        self.fMaturityAmountLineEdit.setReadOnly(True)
        self.fMaturityAmountLineEdit.setObjectName("fMaturityAmountLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fMaturityAmountLineEdit)
        self.label_14 = QtWidgets.QLabel(self.fixedDepositWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.fInterestRateLineEdit = QtWidgets.QLineEdit(self.fixedDepositWidget)
        self.fInterestRateLineEdit.setReadOnly(True)
        self.fInterestRateLineEdit.setObjectName("fInterestRateLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fInterestRateLineEdit)
        self.fixedDepositVerticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addWidget(self.fixedDepositWidget)
        self.line = QtWidgets.QFrame(self.accountsTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.savingWidget = QtWidgets.QWidget(self.accountsTab)
        self.savingWidget.setObjectName("savingWidget")
        self.savingsVerticalLayout = QtWidgets.QVBoxLayout(self.savingWidget)
        self.savingsVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.savingsVerticalLayout.setObjectName("savingsVerticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.savingWidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.sDeletePushButton = QtWidgets.QPushButton(self.savingWidget)
        self.sDeletePushButton.setObjectName("sDeletePushButton")
        self.horizontalLayout_10.addWidget(self.sDeletePushButton)
        self.savingsVerticalLayout.addLayout(self.horizontalLayout_10)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.savingWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.sAccountNoLineEdit = QtWidgets.QLineEdit(self.savingWidget)
        self.sAccountNoLineEdit.setObjectName("sAccountNoLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sAccountNoLineEdit)
        self.label_11 = QtWidgets.QLabel(self.savingWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.sBalanceLineEdit = QtWidgets.QLineEdit(self.savingWidget)
        self.sBalanceLineEdit.setObjectName("sBalanceLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sBalanceLineEdit)
        self.label_12 = QtWidgets.QLabel(self.savingWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.sOpeningDateEdit = QtWidgets.QDateEdit(self.savingWidget)
        self.sOpeningDateEdit.setObjectName("sOpeningDateEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sOpeningDateEdit)
        self.label_13 = QtWidgets.QLabel(self.savingWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.sInterestRateLineEdit = QtWidgets.QLineEdit(self.savingWidget)
        self.sInterestRateLineEdit.setObjectName("sInterestRateLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sInterestRateLineEdit)
        self.savingsVerticalLayout.addLayout(self.formLayout_3)
        self.verticalLayout_2.addWidget(self.savingWidget)
        self.line_2 = QtWidgets.QFrame(self.accountsTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.recurringWidget = QtWidgets.QWidget(self.accountsTab)
        self.recurringWidget.setObjectName("recurringWidget")
        self.recurringVerticalLayout = QtWidgets.QVBoxLayout(self.recurringWidget)
        self.recurringVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.recurringVerticalLayout.setObjectName("recurringVerticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.recurringWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.rDushButton = QtWidgets.QPushButton(self.recurringWidget)
        self.rDushButton.setObjectName("rDushButton")
        self.horizontalLayout_11.addWidget(self.rDushButton)
        self.recurringVerticalLayout.addLayout(self.horizontalLayout_11)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtWidgets.QLabel(self.recurringWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.recurringWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.recurringWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.recurringWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.recurringWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.recurringWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.rAccountNoLineEdit = QtWidgets.QLineEdit(self.recurringWidget)
        self.rAccountNoLineEdit.setReadOnly(True)
        self.rAccountNoLineEdit.setObjectName("rAccountNoLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rAccountNoLineEdit)
        self.rInstallmentLineEdit = QtWidgets.QLineEdit(self.recurringWidget)
        self.rInstallmentLineEdit.setReadOnly(True)
        self.rInstallmentLineEdit.setObjectName("rInstallmentLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rInstallmentLineEdit)
        self.rOpeningDateEdit = QtWidgets.QDateEdit(self.recurringWidget)
        self.rOpeningDateEdit.setReadOnly(True)
        self.rOpeningDateEdit.setObjectName("rOpeningDateEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rOpeningDateEdit)
        self.rMaturityDateEdit = QtWidgets.QDateEdit(self.recurringWidget)
        self.rMaturityDateEdit.setReadOnly(True)
        self.rMaturityDateEdit.setObjectName("rMaturityDateEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rMaturityDateEdit)
        self.rInterestRateLineEdit = QtWidgets.QLineEdit(self.recurringWidget)
        self.rInterestRateLineEdit.setReadOnly(True)
        self.rInterestRateLineEdit.setObjectName("rInterestRateLineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rInterestRateLineEdit)
        self.rMaturityAmountLineEdit = QtWidgets.QLineEdit(self.recurringWidget)
        self.rMaturityAmountLineEdit.setReadOnly(True)
        self.rMaturityAmountLineEdit.setObjectName("rMaturityAmountLineEdit")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rMaturityAmountLineEdit)
        self.recurringVerticalLayout.addLayout(self.formLayout_4)
        self.verticalLayout_2.addWidget(self.recurringWidget)
        self.line_3 = QtWidgets.QFrame(self.accountsTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.createAccountPushButton = QtWidgets.QPushButton(self.accountsTab)
        self.createAccountPushButton.setObjectName("createAccountPushButton")
        self.horizontalLayout_3.addWidget(self.createAccountPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.accountsTab, "")
        self.transactionTab = QtWidgets.QWidget()
        self.transactionTab.setObjectName("transactionTab")
        self.tabWidget.addTab(self.transactionTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(memberPage)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(memberPage)

    def retranslateUi(self, memberPage):
        _translate = QtCore.QCoreApplication.translate
        memberPage.setWindowTitle(_translate("memberPage", "memberName"))
        self.label_name.setText(_translate("memberPage", "NAME :"))
        self.label_nameField.setText(_translate("memberPage", "TextLabel"))
        self.label_fatherHusband.setText(_translate("memberPage", "FATHER/HUSBAND :"))
        self.label_fatherHusbandField.setText(_translate("memberPage", "TextLabel"))
        self.label_dob.setText(_translate("memberPage", "DOB :"))
        self.label_dobField.setText(_translate("memberPage", "TextLabel"))
        self.label_gender.setText(_translate("memberPage", "GENDER :"))
        self.label_genderField.setText(_translate("memberPage", "TextLabel"))
        self.label_village.setText(_translate("memberPage", "VILLAGE :"))
        self.label_villageField.setText(_translate("memberPage", "TextLabel"))
        self.label_block.setText(_translate("memberPage", "BLOCK :"))
        self.label_blockField.setText(_translate("memberPage", "TextLabel"))
        self.label_district.setText(_translate("memberPage", "DISTRICT :"))
        self.label_districtField.setText(_translate("memberPage", "TextLabel"))
        self.label_state.setText(_translate("memberPage", "STATE :"))
        self.label_stateField.setText(_translate("memberPage", "TextLabel"))
        self.label_pincode.setText(_translate("memberPage", "PINCODE :"))
        self.label_pincodeField.setText(_translate("memberPage", "TextLabel"))
        self.label_mobile.setText(_translate("memberPage", "MOBILE :"))
        self.label_mobileField.setText(_translate("memberPage", "TextLabel"))
        self.label_email.setText(_translate("memberPage", "EMAIL :"))
        self.label_emailField.setText(_translate("memberPage", "TextLabel"))
        self.label_profession.setText(_translate("memberPage", "PROFESSION :"))
        self.label_professionField.setText(_translate("memberPage", "TextLabel"))
        self.label_office.setText(_translate("memberPage", "OFFICE :"))
        self.label_officeField.setText(_translate("memberPage", "TextLabel"))
        self.label_membershipType.setText(_translate("memberPage", "MEMBERSHIP TYPE :"))
        self.label_membershipTypeField.setText(_translate("memberPage", "TextLabel"))
        self.label_shares.setText(_translate("memberPage", "SHARES :"))
        self.label_sharesField.setText(_translate("memberPage", "TextLabel"))
        self.label_openingDate.setText(_translate("memberPage", "OPENING DATE :"))
        self.label_openingDateField.setText(_translate("memberPage", "TextLabel"))
        self.editButton.setText(_translate("memberPage", "Edit"))
        self.label.setText(_translate("memberPage", "Type of Id Proof:"))
        self.label_idProof.setText(_translate("memberPage", "TextLabel"))
        self.label_2.setText(_translate("memberPage", "Id Number:"))
        self.label_idNumber.setText(_translate("memberPage", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _translate("memberPage", "Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loanTab), _translate("memberPage", "Loans"))
        self.label_3.setText(_translate("memberPage", "Fixed Deposit:"))
        self.fDeletePushButton.setText(_translate("memberPage", "Delete"))
        self.label_4.setText(_translate("memberPage", "Account No:"))
        self.label_5.setText(_translate("memberPage", "Principal Amount:"))
        self.label_7.setText(_translate("memberPage", "Opening Date:"))
        self.label_6.setText(_translate("memberPage", "Maturity Date:"))
        self.label_8.setText(_translate("memberPage", "Maturity Amount:"))
        self.label_14.setText(_translate("memberPage", "Interest Rate:"))
        self.label_22.setText(_translate("memberPage", "Saving:"))
        self.sDeletePushButton.setText(_translate("memberPage", "Delete"))
        self.label_10.setText(_translate("memberPage", "Account No:"))
        self.label_11.setText(_translate("memberPage", "Balance:"))
        self.label_12.setText(_translate("memberPage", "Opening Date:"))
        self.label_13.setText(_translate("memberPage", "Interest Rate:"))
        self.label_9.setText(_translate("memberPage", "Recurring:"))
        self.rDushButton.setText(_translate("memberPage", "Delete"))
        self.label_16.setText(_translate("memberPage", "Account No:"))
        self.label_17.setText(_translate("memberPage", "Payable Installment:"))
        self.label_18.setText(_translate("memberPage", "Opening Date:"))
        self.label_19.setText(_translate("memberPage", "Interest Rate:"))
        self.label_20.setText(_translate("memberPage", "Maturity Date:"))
        self.label_21.setText(_translate("memberPage", "Maturity Amount:"))
        self.createAccountPushButton.setText(_translate("memberPage", "Create new account"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountsTab), _translate("memberPage", "Accounts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transactionTab), _translate("memberPage", "Transactions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    memberPage = QtWidgets.QWidget()
    ui = Ui_memberPage()
    ui.setupUi(memberPage)
    memberPage.show()
    sys.exit(app.exec_())

