# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pages/UI/newLoan.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(446, 354)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.memberIdLineEdit = QtWidgets.QLineEdit(Form)
        self.memberIdLineEdit.setPlaceholderText("")
        self.memberIdLineEdit.setObjectName("memberIdLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.memberIdLineEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nameLineEdit = QtWidgets.QLineEdit(Form)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.phoneLineEdit = QtWidgets.QLineEdit(Form)
        self.phoneLineEdit.setObjectName("phoneLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phoneLineEdit)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.loanTypeComboBox = QtWidgets.QComboBox(Form)
        self.loanTypeComboBox.setEditable(True)
        self.loanTypeComboBox.setObjectName("loanTypeComboBox")
        self.loanTypeComboBox.addItem("")
        self.loanTypeComboBox.addItem("")
        self.loanTypeComboBox.addItem("")
        self.loanTypeComboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.loanTypeComboBox)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.interestRateLineEdit = QtWidgets.QLineEdit(Form)
        self.interestRateLineEdit.setObjectName("interestRateLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.interestRateLineEdit)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.compoundMethodComboBox = QtWidgets.QComboBox(Form)
        self.compoundMethodComboBox.setObjectName("compoundMethodComboBox")
        self.compoundMethodComboBox.addItem("")
        self.compoundMethodComboBox.addItem("")
        self.compoundMethodComboBox.addItem("")
        self.compoundMethodComboBox.addItem("")
        self.compoundMethodComboBox.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.compoundMethodComboBox)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.principalAmountLineEdit = QtWidgets.QLineEdit(Form)
        self.principalAmountLineEdit.setObjectName("principalAmountLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.principalAmountLineEdit)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.termLineEdit = QtWidgets.QLineEdit(Form)
        self.termLineEdit.setObjectName("termLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.termLineEdit)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.submitPushButton = QtWidgets.QPushButton(Form)
        self.submitPushButton.setObjectName("submitPushButton")
        self.verticalLayout.addWidget(self.submitPushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "New Loan"))
        self.label.setText(_translate("Form", "Member Id:"))
        self.label_2.setText(_translate("Form", "Name:"))
        self.label_3.setText(_translate("Form", "Phone:"))
        self.label_4.setText(_translate("Form", "Loan Type:"))
        self.loanTypeComboBox.setItemText(0, _translate("Form", "House Loan"))
        self.loanTypeComboBox.setItemText(1, _translate("Form", "Marriage Loan"))
        self.loanTypeComboBox.setItemText(2, _translate("Form", "Study Loan"))
        self.loanTypeComboBox.setItemText(3, _translate("Form", "Agriculture Loan"))
        self.label_5.setText(_translate("Form", "Interest Rate:"))
        self.interestRateLineEdit.setPlaceholderText(_translate("Form", "in %"))
        self.label_6.setText(_translate("Form", "Coumpound Method:"))
        self.compoundMethodComboBox.setItemText(0, _translate("Form", "1 month"))
        self.compoundMethodComboBox.setItemText(1, _translate("Form", "2 months"))
        self.compoundMethodComboBox.setItemText(2, _translate("Form", "3 months"))
        self.compoundMethodComboBox.setItemText(3, _translate("Form", "6 months"))
        self.compoundMethodComboBox.setItemText(4, _translate("Form", "12 months"))
        self.label_7.setText(_translate("Form", "Principal Amount:"))
        self.principalAmountLineEdit.setPlaceholderText(_translate("Form", "0.0"))
        self.label_8.setText(_translate("Form", "Term:"))
        self.termLineEdit.setPlaceholderText(_translate("Form", "in months"))
        self.label_9.setText(_translate("Form", "Date:"))
        self.dateEdit.setDisplayFormat(_translate("Form", "d/M/yy"))
        self.submitPushButton.setText(_translate("Form", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

