# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transfer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fromBalanceLabel(object):
    def setupUi(self, fromBalanceLabel):
        fromBalanceLabel.setObjectName("fromBalanceLabel")
        fromBalanceLabel.resize(801, 332)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(fromBalanceLabel)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.label = QtWidgets.QLabel(fromBalanceLabel)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fromMemberLineEdit = QtWidgets.QLineEdit(fromBalanceLabel)
        self.fromMemberLineEdit.setObjectName("fromMemberLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fromMemberLineEdit)
        self.label_5 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.formNameLineEdit = QtWidgets.QLineEdit(fromBalanceLabel)
        self.formNameLineEdit.setObjectName("formNameLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.formNameLineEdit)
        self.label_6 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.fromBalanceLabel_2 = QtWidgets.QLabel(fromBalanceLabel)
        self.fromBalanceLabel_2.setStyleSheet("background-color: white\n"
"")
        self.fromBalanceLabel_2.setObjectName("fromBalanceLabel_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fromBalanceLabel_2)
        self.label_13 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.fromAmountLineEdit = QtWidgets.QLineEdit(fromBalanceLabel)
        self.fromAmountLineEdit.setObjectName("fromAmountLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fromAmountLineEdit)
        self.label_15 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.dateEdit = QtWidgets.QDateEdit(fromBalanceLabel)
        self.dateEdit.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.fromPhotoLabel = QtWidgets.QLabel(fromBalanceLabel)
        self.fromPhotoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.fromPhotoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.fromPhotoLabel.setStyleSheet("background-color: white")
        self.fromPhotoLabel.setText("")
        self.fromPhotoLabel.setPixmap(QtGui.QPixmap(":/image res/pranavDP.jpg"))
        self.fromPhotoLabel.setScaledContents(True)
        self.fromPhotoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.fromPhotoLabel.setObjectName("fromPhotoLabel")
        self.verticalLayout.addWidget(self.fromPhotoLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(fromBalanceLabel)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setHorizontalSpacing(6)
        self.formLayout_3.setVerticalSpacing(20)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_7 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.toMemberLineEdit = QtWidgets.QLineEdit(fromBalanceLabel)
        self.toMemberLineEdit.setObjectName("toMemberLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.toMemberLineEdit)
        self.toNameLineEdit = QtWidgets.QLineEdit(fromBalanceLabel)
        self.toNameLineEdit.setObjectName("toNameLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.toNameLineEdit)
        self.label_10 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.accountComboBox = QtWidgets.QComboBox(fromBalanceLabel)
        self.accountComboBox.setObjectName("accountComboBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.accountComboBox)
        self.label_14 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.toBalanceLabel = QtWidgets.QLabel(fromBalanceLabel)
        self.toBalanceLabel.setStyleSheet("background-color: white\n"
"")
        self.toBalanceLabel.setObjectName("toBalanceLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.toBalanceLabel)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(fromBalanceLabel)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.toPhotoLabel = QtWidgets.QLabel(fromBalanceLabel)
        self.toPhotoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.toPhotoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.toPhotoLabel.setStyleSheet("background-color: white")
        self.toPhotoLabel.setText("")
        self.toPhotoLabel.setPixmap(QtGui.QPixmap(":/image res/pranavDP.jpg"))
        self.toPhotoLabel.setScaledContents(True)
        self.toPhotoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toPhotoLabel.setObjectName("toPhotoLabel")
        self.verticalLayout_3.addWidget(self.toPhotoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.submitPushButton = QtWidgets.QPushButton(fromBalanceLabel)
        self.submitPushButton.setObjectName("submitPushButton")
        self.verticalLayout_3.addWidget(self.submitPushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(fromBalanceLabel)
        QtCore.QMetaObject.connectSlotsByName(fromBalanceLabel)

    def retranslateUi(self, fromBalanceLabel):
        _translate = QtCore.QCoreApplication.translate
        fromBalanceLabel.setWindowTitle(_translate("fromBalanceLabel", "Form"))
        self.label_9.setText(_translate("fromBalanceLabel", "From"))
        self.label.setText(_translate("fromBalanceLabel", "Member Id:"))
        self.label_5.setText(_translate("fromBalanceLabel", "Name:"))
        self.label_6.setText(_translate("fromBalanceLabel", "Current Balance:"))
        self.fromBalanceLabel_2.setText(_translate("fromBalanceLabel", "0.0"))
        self.label_13.setText(_translate("fromBalanceLabel", "Amount:"))
        self.label_15.setText(_translate("fromBalanceLabel", "Date:"))
        self.dateEdit.setDisplayFormat(_translate("fromBalanceLabel", "d/M/yy"))
        self.label_11.setText(_translate("fromBalanceLabel", "Photo"))
        self.label_2.setText(_translate("fromBalanceLabel", "Member Id:"))
        self.label_7.setText(_translate("fromBalanceLabel", "Name:"))
        self.label_8.setText(_translate("fromBalanceLabel", "Select account"))
        self.label_10.setText(_translate("fromBalanceLabel", "To"))
        self.label_14.setText(_translate("fromBalanceLabel", "New Balance:"))
        self.toBalanceLabel.setText(_translate("fromBalanceLabel", "0.0"))
        self.label_12.setText(_translate("fromBalanceLabel", "Photo"))
        self.submitPushButton.setText(_translate("fromBalanceLabel", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fromBalanceLabel = QtWidgets.QWidget()
    ui = Ui_fromBalanceLabel()
    ui.setupUi(fromBalanceLabel)
    fromBalanceLabel.show()
    sys.exit(app.exec_())

