# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 588)
        MainWindow.setAcceptDrops(False)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 19))
        self.menubar.setObjectName("menubar")
        self.menuMembers = QtWidgets.QMenu(self.menubar)
        self.menuMembers.setObjectName("menuMembers")
        self.menuLoan = QtWidgets.QMenu(self.menubar)
        self.menuLoan.setObjectName("menuLoan")
        self.menuTransaction = QtWidgets.QMenu(self.menubar)
        self.menuTransaction.setObjectName("menuTransaction")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuAccounts = QtWidgets.QMenu(self.menuReport)
        self.menuAccounts.setObjectName("menuAccounts")
        self.menuLoan_2 = QtWidgets.QMenu(self.menuReport)
        self.menuLoan_2.setObjectName("menuLoan_2")
        self.menuBackup = QtWidgets.QMenu(self.menubar)
        self.menuBackup.setObjectName("menuBackup")
        self.menuExpense = QtWidgets.QMenu(self.menubar)
        self.menuExpense.setObjectName("menuExpense")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_New = QtWidgets.QAction(MainWindow)
        self.actionAdd_New.setObjectName("actionAdd_New")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionNew_Loan = QtWidgets.QAction(MainWindow)
        self.actionNew_Loan.setObjectName("actionNew_Loan")
        self.actionView_Loans = QtWidgets.QAction(MainWindow)
        self.actionView_Loans.setObjectName("actionView_Loans")
        self.actionVoucher = QtWidgets.QAction(MainWindow)
        self.actionVoucher.setObjectName("actionVoucher")
        self.actionPay_Slip = QtWidgets.QAction(MainWindow)
        self.actionPay_Slip.setObjectName("actionPay_Slip")
        self.actionBalance_Sheet = QtWidgets.QAction(MainWindow)
        self.actionBalance_Sheet.setObjectName("actionBalance_Sheet")
        self.actionProfit_and_Loss = QtWidgets.QAction(MainWindow)
        self.actionProfit_and_Loss.setObjectName("actionProfit_and_Loss")
        self.actionReceipt_and_Disbursment = QtWidgets.QAction(MainWindow)
        self.actionReceipt_and_Disbursment.setObjectName("actionReceipt_and_Disbursment")
        self.actionShareholders = QtWidgets.QAction(MainWindow)
        self.actionShareholders.setObjectName("actionShareholders")
        self.actionTerm_Deposit_Account = QtWidgets.QAction(MainWindow)
        self.actionTerm_Deposit_Account.setObjectName("actionTerm_Deposit_Account")
        self.actionStationary = QtWidgets.QAction(MainWindow)
        self.actionStationary.setObjectName("actionStationary")
        self.actionFurniture = QtWidgets.QAction(MainWindow)
        self.actionFurniture.setObjectName("actionFurniture")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionRecurring_Deposit = QtWidgets.QAction(MainWindow)
        self.actionRecurring_Deposit.setObjectName("actionRecurring_Deposit")
        self.actionFixed_Deposit = QtWidgets.QAction(MainWindow)
        self.actionFixed_Deposit.setObjectName("actionFixed_Deposit")
        self.actionSavings = QtWidgets.QAction(MainWindow)
        self.actionSavings.setObjectName("actionSavings")
        self.actionStationary_2 = QtWidgets.QAction(MainWindow)
        self.actionStationary_2.setObjectName("actionStationary_2")
        self.actionAdvance = QtWidgets.QAction(MainWindow)
        self.actionAdvance.setObjectName("actionAdvance")
        self.actionOutstanding = QtWidgets.QAction(MainWindow)
        self.actionOutstanding.setObjectName("actionOutstanding")
        self.actionBank = QtWidgets.QAction(MainWindow)
        self.actionBank.setObjectName("actionBank")
        self.actionNew_Expense = QtWidgets.QAction(MainWindow)
        self.actionNew_Expense.setObjectName("actionNew_Expense")
        self.actionView_Expense = QtWidgets.QAction(MainWindow)
        self.actionView_Expense.setObjectName("actionView_Expense")
        self.actionSync = QtWidgets.QAction(MainWindow)
        self.actionSync.setObjectName("actionSync")
        self.actionRestore = QtWidgets.QAction(MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSupport = QtWidgets.QAction(MainWindow)
        self.actionSupport.setObjectName("actionSupport")
        self.actionMisc = QtWidgets.QAction(MainWindow)
        self.actionMisc.setObjectName("actionMisc")
        self.menuMembers.addAction(self.actionAdd_New)
        self.menuMembers.addAction(self.actionFind)
        self.menuLoan.addAction(self.actionNew_Loan)
        self.menuLoan.addAction(self.actionView_Loans)
        self.menuTransaction.addAction(self.actionVoucher)
        self.menuTransaction.addAction(self.actionPay_Slip)
        self.menuAccounts.addAction(self.actionRecurring_Deposit)
        self.menuAccounts.addAction(self.actionFixed_Deposit)
        self.menuAccounts.addAction(self.actionSavings)
        self.menuLoan_2.addAction(self.actionAdvance)
        self.menuLoan_2.addAction(self.actionOutstanding)
        self.menuReport.addAction(self.menuAccounts.menuAction())
        self.menuReport.addAction(self.menuLoan_2.menuAction())
        self.menuReport.addAction(self.actionBalance_Sheet)
        self.menuReport.addAction(self.actionProfit_and_Loss)
        self.menuReport.addAction(self.actionReceipt_and_Disbursment)
        self.menuReport.addAction(self.actionShareholders)
        self.menuReport.addAction(self.actionTerm_Deposit_Account)
        self.menuReport.addAction(self.actionMisc)
        self.menuReport.addSeparator()
        self.menuBackup.addAction(self.actionRestore)
        self.menuBackup.addAction(self.actionSync)
        self.menuExpense.addAction(self.actionNew_Expense)
        self.menuExpense.addAction(self.actionView_Expense)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionSupport)
        self.menubar.addAction(self.menuMembers.menuAction())
        self.menubar.addAction(self.menuLoan.menuAction())
        self.menubar.addAction(self.menuTransaction.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuExpense.menuAction())
        self.menubar.addAction(self.menuBackup.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDoName"))
        self.menuMembers.setTitle(_translate("MainWindow", "Members"))
        self.menuLoan.setTitle(_translate("MainWindow", "Loan"))
        self.menuTransaction.setTitle(_translate("MainWindow", "Transaction"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuAccounts.setTitle(_translate("MainWindow", "Accounts"))
        self.menuLoan_2.setTitle(_translate("MainWindow", "Loan"))
        self.menuBackup.setTitle(_translate("MainWindow", "Backup"))
        self.menuExpense.setTitle(_translate("MainWindow", "Expense"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.actionAdd_New.setText(_translate("MainWindow", "Add New"))
        self.actionFind.setText(_translate("MainWindow", "Find Member"))
        self.actionNew_Loan.setText(_translate("MainWindow", "New Loan"))
        self.actionView_Loans.setText(_translate("MainWindow", "View Loan"))
        self.actionVoucher.setText(_translate("MainWindow", "Voucher"))
        self.actionPay_Slip.setText(_translate("MainWindow", "Pay Slip"))
        self.actionBalance_Sheet.setText(_translate("MainWindow", "Balance Sheet"))
        self.actionProfit_and_Loss.setText(_translate("MainWindow", "Profit and Loss"))
        self.actionReceipt_and_Disbursment.setText(_translate("MainWindow", "Receipt and Disbursment"))
        self.actionShareholders.setText(_translate("MainWindow", "Shareholders"))
        self.actionTerm_Deposit_Account.setText(_translate("MainWindow", "Term Deposit Accounts"))
        self.actionStationary.setText(_translate("MainWindow", "Stationary"))
        self.actionFurniture.setText(_translate("MainWindow", "Furniture"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))
        self.actionRecurring_Deposit.setText(_translate("MainWindow", "Recurring Deposit"))
        self.actionFixed_Deposit.setText(_translate("MainWindow", "Fixed Deposit"))
        self.actionSavings.setText(_translate("MainWindow", "Savings "))
        self.actionStationary_2.setText(_translate("MainWindow", "Stationary"))
        self.actionAdvance.setText(_translate("MainWindow", "Advanced"))
        self.actionOutstanding.setText(_translate("MainWindow", "Outstanding"))
        self.actionBank.setText(_translate("MainWindow", "Bank"))
        self.actionNew_Expense.setText(_translate("MainWindow", "New Expense"))
        self.actionView_Expense.setText(_translate("MainWindow", "View Expense"))
        self.actionSync.setText(_translate("MainWindow", "Sync"))
        self.actionRestore.setText(_translate("MainWindow", "Restore"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSupport.setText(_translate("MainWindow", "Support"))
        self.actionMisc.setText(_translate("MainWindow", "Misc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

